### ISSUE TITLE
Relations with thrift.NewTHttpClient

### ISSUE THREAD

**Issue by BBDXF** [upfluence/thrift-http-go#2]
it has any relations with `thrift.NewTHttpClient`?  
whether the server can be used with `thrift.NewTHttpClient`?

look forward to your replay

**Comment by AlexisMontagne** [comment]
The `HTTPClient` implemented here is fully compatible with the HTTP transport implemented  in the  thrift repository. The point of this repo is to add some features to the client (retry system, timeouts ...)
